
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.TransferHandler;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ss
 */
public class myGameFrame extends javax.swing.JFrame {

    /**
     * Creates new form myGameFrame
     */
    ThreeCard [] array = new ThreeCard[5]; 
       
    private int counter = 0;
     ThreeCard threeCard1 , threeCard2 , threeCard3;
    myTransferHandler mytransporthandler; 
    object_card card2 , card3 , card4 , card5 , card6 , card7 , card8 , card9 , card10 , card11 , card12 , card13 , card14;
    object_card [] carrd = new object_card [33];
    public myGameFrame() {
        initComponents();
       
        try {
            card2 = new object_card ("2" , "spades" , 2 , ImageIO.read(new File ("2.png")));
            card3 = new object_card ("3" , "spades" , 3 , ImageIO.read(new File ("3.png")));
            card4 = new object_card ("4" , "spades" , 4 , ImageIO.read(new File ("4.png")));
            card5 = new object_card ("5" , "spades" , 5 , ImageIO.read(new File ("5.png")));
            card6 = new object_card ("6" , "spades" , 6 , ImageIO.read(new File ("6.png")));
            card7 = new object_card ("7" , "spades" , 7 , ImageIO.read(new File ("7.png")));
            card8 = new object_card ("8" , "spades" , 8 , ImageIO.read(new File ("8.png")));
            card9 = new object_card ("9" , "spades" , 9 , ImageIO.read(new File ("9.png")));
            card10 = new object_card ("10" , "spades" , 10 , ImageIO.read(new File ("10.png")));
            card11 = new object_card ("Jack" , "spades" , 11 , ImageIO.read(new File ("jack.png")));
            card12 = new object_card ("Queen" , "spades" , 12 , ImageIO.read(new File ("queen.png")));
            card13 = new object_card ("King" , "spades" , 13 , ImageIO.read(new File ("king.png")));
            card14 = new object_card ("Ace" , "spades" , 14 , ImageIO.read(new File ("ace.png")));
        } catch (IOException e) {}
        
        carrd[0] = card2;
        carrd[1] = card3;
        carrd[2] = card4;
        carrd[3] = card5;
        carrd[4] = card6;
        carrd[5] = card7;
        carrd[6] = card8;
        carrd[7] = card9;
        carrd[8] = card10;
        carrd[9] = card11;
        carrd[10] = card12;
        carrd[11] = card13;
        carrd[12] = card14;
        Integer [] arr = new Integer[] {1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10 , 11 , 12 , 13};
        mytransporthandler = new myTransferHandler ("icon"); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        MakerLabel1 = new javax.swing.JLabel();
        MakerLabel2 = new javax.swing.JLabel();
        MakerLabel3 = new javax.swing.JLabel();
        MakerLabel4 = new javax.swing.JLabel();
        MakerLabel5 = new javax.swing.JLabel();
        MakerLabel6 = new javax.swing.JLabel();
        MakerLabel7 = new javax.swing.JLabel();
        MakerLabel8 = new javax.swing.JLabel();
        MakerLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        myFirstThreeCardLabelNo2 = new javax.swing.JLabel();
        myFirstThreeCardLabelNo1 = new javax.swing.JLabel();
        myFirstThreeCardLabelNo3 = new javax.swing.JLabel();
        computerFirstThreeCardNo3 = new javax.swing.JLabel();
        computerFirstThreeCardLabelNo1 = new javax.swing.JLabel();
        computerFirstThreeCardLabelNo2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ss\\Desktop\\Capture.PNG")); // NOI18N
        jLabel10.setText("jLabel1");
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel10MouseDragged(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ss\\Desktop\\Capture.PNG")); // NOI18N
        jLabel11.setText("jLabel1");
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel11MouseDragged(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ss\\Desktop\\Capture.PNG")); // NOI18N
        jLabel12.setText("jLabel1");
        jLabel12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel12MouseDragged(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\ss\\Desktop\\Capture.PNG")); // NOI18N
        jLabel19.setText("jLabel1");
        jLabel19.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel19MouseDragged(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\ss\\Desktop\\Capture.PNG")); // NOI18N
        jLabel20.setText("jLabel1");
        jLabel20.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel20MouseDragged(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\ss\\Desktop\\Capture.PNG")); // NOI18N
        jLabel21.setText("jLabel1");
        jLabel21.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel21MouseDragged(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        jLabel3.setText("jLabel1");
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        jLabel4.setText("jLabel1");
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        jLabel5.setText("jLabel1");
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        jLabel6.setText("jLabel1");
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel6MouseDragged(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        jLabel7.setText("jLabel1");
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel7MouseDragged(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        jLabel8.setText("jLabel1");
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel8MouseDragged(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        jLabel9.setText("jLabel1");
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel9MouseDragged(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ss\\Desktop\\deal.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        MakerLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        MakerLabel1.setText("jLabel1");
        MakerLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MakerLabel1MouseDragged(evt);
            }
        });

        MakerLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        MakerLabel2.setText("jLabel1");
        MakerLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MakerLabel2MouseDragged(evt);
            }
        });

        MakerLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        MakerLabel3.setText("jLabel1");
        MakerLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MakerLabel3MouseDragged(evt);
            }
        });

        MakerLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        MakerLabel4.setText("jLabel1");
        MakerLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MakerLabel4MouseDragged(evt);
            }
        });

        MakerLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        MakerLabel5.setText("jLabel1");
        MakerLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MakerLabel5MouseDragged(evt);
            }
        });

        MakerLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        MakerLabel6.setText("jLabel1");
        MakerLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MakerLabel6MouseDragged(evt);
            }
        });

        MakerLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        MakerLabel7.setText("jLabel1");
        MakerLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MakerLabel7MouseDragged(evt);
            }
        });

        MakerLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        MakerLabel8.setText("jLabel1");
        MakerLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MakerLabel8MouseDragged(evt);
            }
        });

        MakerLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        MakerLabel9.setText("jLabel1");
        MakerLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MakerLabel9MouseDragged(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 153));
        jButton2.setText("Done");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        myFirstThreeCardLabelNo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N

        myFirstThreeCardLabelNo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N

        myFirstThreeCardLabelNo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        myFirstThreeCardLabelNo3.setText("jLabel13");

        computerFirstThreeCardNo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N

        computerFirstThreeCardLabelNo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N

        computerFirstThreeCardLabelNo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 204, 0));
        jButton3.setText("Deal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(myFirstThreeCardLabelNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(myFirstThreeCardLabelNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(myFirstThreeCardLabelNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MakerLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MakerLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MakerLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(MakerLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MakerLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MakerLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(MakerLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MakerLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(computerFirstThreeCardLabelNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(computerFirstThreeCardLabelNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(computerFirstThreeCardNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MakerLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(myFirstThreeCardLabelNo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myFirstThreeCardLabelNo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myFirstThreeCardLabelNo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(computerFirstThreeCardLabelNo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(computerFirstThreeCardNo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(computerFirstThreeCardLabelNo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MakerLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MakerLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MakerLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MakerLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MakerLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MakerLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MakerLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MakerLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MakerLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
                    
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
        
    }//GEN-LAST:event_jLabel9MouseDragged

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
        
    }//GEN-LAST:event_jLabel3MouseDragged

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
        
    }//GEN-LAST:event_jLabel4MouseDragged

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
        
    }//GEN-LAST:event_jLabel5MouseDragged

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
        
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
        
    }//GEN-LAST:event_jLabel6MouseDragged

    private void jLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
        
    }//GEN-LAST:event_jLabel7MouseDragged

    private void jLabel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
        
    }//GEN-LAST:event_jLabel8MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        array[0] = null; 
        array[1] = null; 
        array[2] = null; 
        counter = 0;
        try {
            MakerLabel1.setIcon(new ImageIcon (ImageIO.read(new File ("Capture.png"))));
            MakerLabel2.setIcon(new ImageIcon (ImageIO.read(new File ("Capture.png"))));
            MakerLabel3.setIcon(new ImageIcon (ImageIO.read(new File ("Capture.png"))));
            MakerLabel4.setIcon(new ImageIcon (ImageIO.read(new File ("Capture.png"))));
            MakerLabel5.setIcon(new ImageIcon (ImageIO.read(new File ("Capture.png"))));
            MakerLabel6.setIcon(new ImageIcon (ImageIO.read(new File ("Capture.png"))));
            MakerLabel7.setIcon(new ImageIcon (ImageIO.read(new File ("Capture.png"))));
            MakerLabel8.setIcon(new ImageIcon (ImageIO.read(new File ("Capture.png"))));
            MakerLabel9.setIcon(new ImageIcon (ImageIO.read(new File ("Capture.png"))));
            myFirstThreeCardLabelNo1.setIcon(new ImageIcon (ImageIO.read(new File ("Capture.png"))));
            myFirstThreeCardLabelNo2.setIcon(new ImageIcon (ImageIO.read(new File ("Capture.png"))));
            myFirstThreeCardLabelNo3.setIcon(new ImageIcon (ImageIO.read(new File ("Capture.png"))));
        } catch (IOException ex) {
            Logger.getLogger(myGameFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jLabel1.setTransferHandler(mytransporthandler);
        jLabel2.setTransferHandler(mytransporthandler);
        jLabel3.setTransferHandler(mytransporthandler);
        jLabel4.setTransferHandler(mytransporthandler);
        jLabel5.setTransferHandler(mytransporthandler);
        jLabel6.setTransferHandler(mytransporthandler);
        jLabel7.setTransferHandler(mytransporthandler);
        jLabel8.setTransferHandler(mytransporthandler);
        jLabel9.setTransferHandler(mytransporthandler);
        
        MakerLabel1.setTransferHandler(mytransporthandler);
        MakerLabel2.setTransferHandler(mytransporthandler);
        MakerLabel3.setTransferHandler(mytransporthandler);
        MakerLabel4.setTransferHandler(mytransporthandler);
        MakerLabel5.setTransferHandler(mytransporthandler);
        MakerLabel6.setTransferHandler(mytransporthandler);
        MakerLabel7.setTransferHandler(mytransporthandler);
        MakerLabel8.setTransferHandler(mytransporthandler);
        MakerLabel9.setTransferHandler(mytransporthandler);
        
        Integer [] arr = new Integer[] {1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10 , 11 , 12 , 13};
        Collections.shuffle(Arrays.asList (arr));
        
                    int index_1st = arr[8];
                    int index_2nd = arr[12];
                    int index_3rd = arr[2]; 


                    int index_4th = arr[1];
                    int index_5th = arr[3];
                    int index_6th = arr[6]; 

                    int index_7th = arr[9];
                    int index_8th = arr[11];
                    int index_9th = arr[10]; 

                    object_card one = carrd[index_1st - 1]; 
                    object_card two = carrd[index_2nd - 1];
                    object_card three = carrd[index_3rd - 1]; 

                    object_card four = carrd[index_4th - 1]; 
                    object_card five = carrd[index_5th - 1];
                    object_card six = carrd[index_6th - 1]; 

                    object_card seven = carrd[index_7th - 1]; 
                    object_card eight = carrd[index_8th - 1];
                    object_card nine = carrd[index_9th - 1]; 

                    jLabel1.setIcon(new ImageIcon (one.bufferedimage));
                    jLabel2.setIcon(new ImageIcon (two.bufferedimage));
                    jLabel3.setIcon(new ImageIcon (three.bufferedimage));
                    jLabel4.setIcon(new ImageIcon (four.bufferedimage));
                    jLabel5.setIcon(new ImageIcon (five.bufferedimage));
                    jLabel6.setIcon(new ImageIcon (six.bufferedimage));
                    jLabel7.setIcon(new ImageIcon (seven.bufferedimage));
                    jLabel8.setIcon(new ImageIcon (eight.bufferedimage));
                    jLabel9.setIcon(new ImageIcon (nine.bufferedimage));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel10MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseDragged

    private void jLabel11MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseDragged

    private void jLabel12MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseDragged

    private void MakerLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MakerLabel1MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
    }//GEN-LAST:event_MakerLabel1MouseDragged

    private void MakerLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MakerLabel2MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
    }//GEN-LAST:event_MakerLabel2MouseDragged

    private void MakerLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MakerLabel3MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
    }//GEN-LAST:event_MakerLabel3MouseDragged

    private void MakerLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MakerLabel4MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
    }//GEN-LAST:event_MakerLabel4MouseDragged

    private void MakerLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MakerLabel5MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
    }//GEN-LAST:event_MakerLabel5MouseDragged

    private void MakerLabel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MakerLabel6MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
    }//GEN-LAST:event_MakerLabel6MouseDragged

    private void jLabel19MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseDragged

    private void jLabel20MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseDragged

    private void jLabel21MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseDragged

    private void MakerLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MakerLabel7MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
    }//GEN-LAST:event_MakerLabel7MouseDragged

    private void MakerLabel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MakerLabel8MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
    }//GEN-LAST:event_MakerLabel8MouseDragged

    private void MakerLabel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MakerLabel9MouseDragged
        JComponent jcomp = (JComponent) evt.getSource(); 
        TransferHandler thand = jcomp.getTransferHandler(); 
        thand.exportAsDrag(jcomp, evt, TransferHandler.MOVE);
    }//GEN-LAST:event_MakerLabel9MouseDragged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        MakerLabel1.setTransferHandler(null);
        MakerLabel2.setTransferHandler(null);
        MakerLabel3.setTransferHandler(null);
        MakerLabel4.setTransferHandler(null);
        MakerLabel5.setTransferHandler(null);
        MakerLabel6.setTransferHandler(null);
        MakerLabel7.setTransferHandler(null);
        MakerLabel8.setTransferHandler(null);
        MakerLabel9.setTransferHandler(null);
        
        ImageIcon testIcon1 = (ImageIcon) MakerLabel1.getIcon();
        ImageIcon testIcon2 = (ImageIcon) MakerLabel2.getIcon(); 
        ImageIcon testIcon3 = (ImageIcon) MakerLabel3.getIcon();
        ImageIcon testIcon4 = (ImageIcon) MakerLabel4.getIcon(); 
        ImageIcon testIcon5 = (ImageIcon) MakerLabel5.getIcon();
        ImageIcon testIcon6 = (ImageIcon) MakerLabel6.getIcon(); 
        ImageIcon testIcon7 = (ImageIcon) MakerLabel7.getIcon();
        ImageIcon testIcon8 = (ImageIcon) MakerLabel8.getIcon(); 
        ImageIcon testIcon9 = (ImageIcon) MakerLabel9.getIcon();
       
        //for the 1st card ///
        object_card ftcf = null , ftcs = null, ftct = null; //firstThreeCardsFirstCard
        object_card stcf = null , stcs = null , stct = null; // secondThreeCardsFirstCard
        object_card ttcf = null, ttcs = null , ttct = null; // thirdThreeCardsFirstCard
        
        for (int i = 0; i < 13; i++) {
            ImageIcon tt = new ImageIcon (carrd[i].bufferedimage);
            //message.setIcon(tt);
             
            if (testIcon1.getImage() == tt.getImage()) {
                ftcf = carrd[i]; 
                break;
            }
        }
        
        for (int i = 0; i < 13; i++) {
            ImageIcon tt = new ImageIcon (carrd[i].bufferedimage); 
            if (testIcon2.getImage() == tt.getImage()) {
                ftcs = carrd[i]; 
                break;
            }
        }
             
        for (int i = 0; i < 13; i++) {
            ImageIcon tt = new ImageIcon (carrd[i].bufferedimage); 
            if (testIcon3.getImage() == tt.getImage()) {
                ftct = carrd[i]; 
                break;
            }
        }
        
        for (int i = 0; i < 13; i++) {
            ImageIcon tt = new ImageIcon (carrd[i].bufferedimage);
            //message.setIcon(tt);
             
            if (testIcon4.getImage() == tt.getImage()) {
                stcf = carrd[i]; 
                break;
            }
        }
        
        for (int i = 0; i < 13; i++) {
            ImageIcon tt = new ImageIcon (carrd[i].bufferedimage); 
            if (testIcon5.getImage() == tt.getImage()) {
                stcs = carrd[i]; 
                break;
            }
        }
             
        for (int i = 0; i < 13; i++) {
            ImageIcon tt = new ImageIcon (carrd[i].bufferedimage); 
            if (testIcon6.getImage() == tt.getImage()) {
                stct = carrd[i]; 
                break;
            }
        }
        
        for (int i = 0; i < 13; i++) {
            ImageIcon tt = new ImageIcon (carrd[i].bufferedimage);
            //message.setIcon(tt);
             
            if (testIcon7.getImage() == tt.getImage()) {
                ttcf = carrd[i]; 
                break;
            }
        }
        
        for (int i = 0; i < 13; i++) {
            ImageIcon tt = new ImageIcon (carrd[i].bufferedimage); 
            if (testIcon8.getImage() == tt.getImage()) {
                ttcs = carrd[i]; 
                break;
            }
        }
             
        for (int i = 0; i < 13; i++) {
            ImageIcon tt = new ImageIcon (carrd[i].bufferedimage); 
            if (testIcon9.getImage() == tt.getImage()) {
                ttct = carrd[i]; 
                break;
            }
        }
        
        threeCard1 = new ThreeCard (ftcf , ftcs , ftct);
        threeCard2 = new ThreeCard (stcf , stcs , stct);
        threeCard3 = new ThreeCard (ttcf , ttcs , ttct);
        System.out.println ("first 3 card .... "); 
        System.out.println (threeCard1.first_card.name + " " + threeCard1.first_card.suit + " " + threeCard1.first_card.value);
        System.out.println (threeCard1.second_card.name + " " + threeCard1.second_card.suit + " " + threeCard1.second_card.value);
        System.out.println (threeCard1.third_card.name + " " + threeCard1.third_card.suit + " " + threeCard1.third_card.value);
        System.out.println ("second 3 card .... "); 
        System.out.println (threeCard2.first_card.name + " " + threeCard2.first_card.suit + " " + threeCard2.first_card.value);
        System.out.println (threeCard2.second_card.name + " " + threeCard2.second_card.suit + " " + threeCard2.second_card.value);
        System.out.println (threeCard2.third_card.name + " " + threeCard2.third_card.suit + " " + threeCard2.third_card.value);
        System.out.println ("second 3 card .... "); 
        System.out.println (threeCard3.first_card.name + " " + threeCard3.first_card.suit + " " + threeCard3.first_card.value);
        System.out.println (threeCard3.second_card.name + " " + threeCard3.second_card.suit + " " + threeCard3.second_card.value);
        System.out.println (threeCard3.third_card.name + " " + threeCard3.third_card.suit + " " + threeCard3.third_card.value);
        System.out.println (""); 
        ThreeCard largest = null , larger = null , large = null; 
        array[0] = threeCard1;
        array[1] = threeCard2; 
        array[2] = threeCard3;
        ThreeCard arr [] = new ThreeCard [3]; 
        ValueFromChecker vc = new ValueFromChecker (array[0] , array[1]);
        ThreeCard ffff = vc.MaxThreeCard(); 
        ValueFromChecker vcc = new ValueFromChecker (ffff , array[2]);
        ThreeCard newt = null; 
        newt = vcc.MaxThreeCard(); 
        largest = newt; 
        int index = 0; 
        for (int i = 0; i < 3; i++) {
            if (array[i] != largest) {
                arr[index++] = array[i];   
            }
        }
        ValueFromChecker vccc = new ValueFromChecker (arr[0] , arr[1]); 
        ThreeCard hh = null; 
        hh = vccc.MaxThreeCard(); 
        if (hh == arr[0]) {
            larger = arr[0]; 
            large = arr[1]; 
        }
        else {
            larger = arr[1]; 
            large = arr[0]; 
        }
        
        array[0] = largest; 
        array[1] = larger; 
        array[2] = large;
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        
    }//GEN-LAST:event_jButton2MouseEntered
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //ValueFromChecker vchecker = new 
        
        if (counter == 0) {
            myFirstThreeCardLabelNo1.setIcon(new ImageIcon (array[0].first_card.bufferedimage));
            myFirstThreeCardLabelNo2.setIcon(new ImageIcon (array[0].second_card.bufferedimage));
            myFirstThreeCardLabelNo3.setIcon(new ImageIcon (array[0].third_card.bufferedimage));
        }
        else if (counter == 1) {
            myFirstThreeCardLabelNo1.setIcon(new ImageIcon (array[1].first_card.bufferedimage));
            myFirstThreeCardLabelNo2.setIcon(new ImageIcon (array[1].second_card.bufferedimage));
            myFirstThreeCardLabelNo3.setIcon(new ImageIcon (array[1].third_card.bufferedimage));
        }
        else if (counter == 2) {
            myFirstThreeCardLabelNo1.setIcon(new ImageIcon (array[2].first_card.bufferedimage));
            myFirstThreeCardLabelNo2.setIcon(new ImageIcon (array[2].second_card.bufferedimage));
            myFirstThreeCardLabelNo3.setIcon(new ImageIcon (array[2].third_card.bufferedimage));
        }
        counter++;
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myGameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MakerLabel1;
    private javax.swing.JLabel MakerLabel2;
    private javax.swing.JLabel MakerLabel3;
    private javax.swing.JLabel MakerLabel4;
    private javax.swing.JLabel MakerLabel5;
    private javax.swing.JLabel MakerLabel6;
    private javax.swing.JLabel MakerLabel7;
    private javax.swing.JLabel MakerLabel8;
    private javax.swing.JLabel MakerLabel9;
    private javax.swing.JLabel computerFirstThreeCardLabelNo1;
    private javax.swing.JLabel computerFirstThreeCardLabelNo2;
    private javax.swing.JLabel computerFirstThreeCardNo3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel myFirstThreeCardLabelNo1;
    private javax.swing.JLabel myFirstThreeCardLabelNo2;
    private javax.swing.JLabel myFirstThreeCardLabelNo3;
    // End of variables declaration//GEN-END:variables
}
