/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testproject__;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.datatransfer.Transferable;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.Timer;
import javax.swing.TransferHandler;
import static javax.swing.TransferHandler.COPY_OR_MOVE;
import static javax.swing.TransferHandler.MOVE;

/**
 *
 * @author ss
 */
class graph extends JComponent implements ActionListener {

    Timer timer = new Timer (5 , this); 
    private int x = 0 , y = 0; 
    public void paintComponent (Graphics g) {
        g.setColor(Color.red);
        g.fillOval(x, y,5 ,5);
    }
    public void actionPerformed(ActionEvent e) {
        x += 3;
        y += 3;
        repaint (); 
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}


public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    
    public NewJFrame1() {
       
        initComponents();
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        click = new javax.swing.JButton();
        secondlabel = new javax.swing.JLabel();
        firstlabel3 = new javax.swing.JLabel();
        test1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ss\\Desktop\\back.PNG")); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        click.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        click.setForeground(new java.awt.Color(0, 153, 102));
        click.setText("click");
        click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        getContentPane().add(click);
        click.setBounds(220, 330, 73, 33);

        secondlabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        secondlabel.setText("empty");
        getContentPane().add(secondlabel);
        secondlabel.setBounds(210, 30, 69, 85);

        firstlabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        firstlabel3.setText("empty");
        getContentPane().add(firstlabel3);
        firstlabel3.setBounds(50, 170, 69, 85);

        test1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        test1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject__/Capture.PNG"))); // NOI18N
        test1.setText("test1");
        getContentPane().add(test1);
        test1.setBounds(220, 280, 69, 85);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickActionPerformed
        
        try {
            test1.setIcon(new ImageIcon (ImageIO.read(new File ("Capture.PNG"))));
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Thread tt; 
        tt = new Thread () { 
            int x = 220 , y = 280;
            public void run () {
                for (int j = 0; j < 3; j++) {
                    for (int i = 1; i <= 10; i++) {
                        test1.setBounds(x - (i * 17) , y - (i * 9) , 69 , 85);
                        try {
                            sleep (50); 
                        }catch (Exception e) {
                            e.printStackTrace();
                        }
                        
                    }
                    test1.setBounds(x , y , 69 , 85);
                    for (int i = 1; i <= 10; i++) {
                        test1.setBounds(x - (i * 1) , y - (i * 25) , 69 , 85);

                        try {
                            sleep (50); 
                        }catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                    test1.setBounds(220, 280, 69, 85);
                    //testl.setBounds(220, 280, 69, 85);
                }//test1.setIcon(null);
        test1.setIcon(null);
            }
            
        }; 
        tt.start();
        
    }//GEN-LAST:event_clickActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton click;
    private javax.swing.JLabel firstlabel3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel secondlabel;
    private javax.swing.JLabel test1;
    // End of variables declaration//GEN-END:variables
}
